const menuOptions = [
    { name: 'X-bacon', price: 34.00, vegan: false, src: './Assets/X-Bacon.jpg' },
    { name: 'X-Bahia', price: 30.00, vegan: false, src: './Assets/X-Bahia.jpg' },
    { name: 'X-Barriga', price: 34, vegan: false, src: './Assets/X-Barriga.jpg' },
    { name: 'X-Chaves Egg', price: 39, vegan: false, src: './Assets/X-Chaves.jpg' },
    { name: 'X-Guloso', price: 50, vegan: false, src: './Assets/X-Guloso.jpg' },
    { name: 'X-Ervas', price: 55, vegan: true, src: './Assets/X-Ervas.jpg' },
    { name: 'X-folhas', price: 30, vegan: true, src: './Assets/X-folhas.jpg' },
    { name: 'X-vegetariano', price: 35, vegan: true, src: './Assets/X-vegetariano.jpg' },
    { name: 'X-abacate', price: 37, vegan: true, src: './Assets/X-abacate.png' },
    { name: 'X-GranBaião', price: 25, vegan: false, src: './Assets/X-GranBaião.jpg' },
    { name: 'X-Tasty', price: 65, vegan: false, src: './Assets/X-Tasty.jpg' },
    { name: 'X-love', price: 60, vegan: false, src: './Assets/X-love.jpg'},
    { name: 'X-Madruga', price: 60, vegan: false, src: './Assets/X-Madruga.jpg'},
    { name: 'X-Grão', price: 45, vegan: true, src: './Assets/X-Grão.png' },
    { name: 'X-monstro', price: 25, vegan: false, src: './Assets/X-Monstro.jpg' },
    { name: 'X-Combo Feliz', price: 25, vegan: false, src: './Assets/X-Combo2.jpg' },
    { name: 'X-Combo Alegre', price: 25, vegan: false, src: './Assets/X-Combo1.jpg' },
    { name: 'X-Combo Festa', price: 25, vegan: false, src: './Assets/X-Combo3.jpg' },
    { name: 'X-Combo Up', price: 25, vegan: false, src: './Assets/X-combo4.jpg' },
    { name: 'X-Combo Crazy', price: 25, vegan: false, src: './Assets/X-combo5.jpg' },
    { name: 'X-Combo Hard', price: 25, vegan: false, src: './Assets/X-combo6.jpg' },

]